"""Tools and technologies added by hand to the skills dictionary: standard name -> other ways postings write it.

Only things with a name of their own belong here: a tool, a product, a language, a platform, a named technique.
General abilities ("communication", "monitoring") are left to the scoring model, which can judge them in context.
Matching ignores letter case, so "Docker" and "docker" are the same entry.
"""

EXTRA_SKILLS = {
    # Containers and platforms
    "Containers": ["container", "containerization", "containerisation", "containerized", "containerised"],
    "Docker": ["Docker Compose", "Dockerfile"],
    "Infrastructure as Code": ["IaC", "infrastructure-as-code"],

    # Delivery and reliability practices
    "CI/CD": ["CICD", "CI CD", "continuous integration", "continuous delivery", "continuous deployment"],
    "DevSecOps": [],
    "Site Reliability Engineering": ["SRE"],

    # Generative AI and machine learning
    "Jev": [],
    "LangGraph": [],
    "LangSmith": [],
    "LlamaIndex": [],
    "CrewAI": [],
    "AutoGen": [],
    "Semantic Kernel": ["Microsoft Semantic Kernel"],
    "Copilot Studio": ["Microsoft Copilot Studio"],
    "Model Context Protocol": ["MCP"],
    "AI Agents": ["agentic AI", "AI agent", "multi-agent", "multi agent", "agentic workflows", "agent systems"],
    "Vector Databases": ["vector database", "vector store", "vector stores", "vector search", "vector DB", "vector DBs"],
    "LLMOps": [],
    "MLOps": [],
    "Hugging Face": ["HuggingFace"],
    "OpenRouter": [],
    "Ollama": [],
    "vLLM": [],
    "Pinecone": [],
    "Weaviate": [],
    "Qdrant": [],
    "Milvus": [],
    "Chroma": ["ChromaDB"],
    "pgvector": [],
    "FAISS": [],
    "OCR": ["optical character recognition"],

    # Data engineering
    "ETL": ["ELT", "ETL/ELT"],
    "Lakehouse": ["data lakehouse"],
    "Medallion Architecture": [],
    "Change Data Capture": ["CDC"],
    "Unity Catalog": [],
    "Delta Live Tables": ["DLT"],
    "Microsoft Fabric": [],
    "OneLake": [],
    "Azure Synapse Analytics": ["Azure Synapse", "Synapse Analytics"],
    "Great Expectations": [],
    "Debezium": [],
    "Kafka Connect": [],

    # Architecture and APIs
    "Microservices": ["microservice", "micro-services"],
    "REST APIs": ["RESTful APIs", "REST API", "RESTful"],
    "gRPC": [],
    "WebSocket": ["WebSockets"],

    # Security and compliance
    "OAuth": ["OAuth2", "OAuth 2.0"],
    "OpenID Connect": ["OIDC"],
    "SAML": [],
    "HIPAA": [],
    "GDPR": [],
    "SOC 2": ["SOC2"],
    "PCI DSS": ["PCI-DSS"],
    "HL7": [],
    "FHIR": [],


    # Languages a tag list writes in ways postings do not
    "Golang": ["Go", "Go lang"],
    "C#": ["C sharp"],
    ".NET": ["dotnet", "dot net"],

    # AI models, assistants and the companies behind them
    "OpenAI": ["Open AI", "OpenAI API", "OpenAI APIs"],
    "ChatGPT": ["Chat GPT"],
    "GPT": ["GPT-3.5", "GPT-4", "GPT-4o", "GPT-4.1", "GPT-5", "GPT models"],
    "Codex": ["OpenAI Codex", "Codex CLI"],
    "Anthropic": ["Anthropic API"],
    "Claude": ["Claude AI", "Anthropic Claude", "Claude Sonnet", "Claude Opus", "Claude Haiku"],
    "Claude Code": ["ClaudeCode", "Claude Code CLI"],
    "Claude Agent SDK": ["Agent SDK"],
    "Gemini": ["Google Gemini", "Gemini Pro", "Gemini API"],
    "Vertex AI": ["Google Vertex AI", "VertexAI"],
    "Azure OpenAI": ["Azure OpenAI Service", "AOAI", "Azure Open AI"],
    "Azure AI Foundry": ["Azure AI Studio", "AI Foundry"],
    "Azure AI Search": ["Azure Cognitive Search", "Cognitive Search"],
    "Azure Machine Learning": ["Azure ML", "AzureML"],
    "GitHub Copilot": ["Copilot", "GH Copilot"],
    "Cursor": ["Cursor IDE", "Cursor AI"],
    "Windsurf": [],
    "Llama": ["LLaMA", "Meta Llama", "Llama 3"],
    "Mistral": ["Mistral AI"],
    "DeepSeek": ["Deep Seek"],
    "Gemma": [],
    "Qwen": [],
    "Grok": [],
    "Cohere": [],
    "Perplexity": [],
    "Stable Diffusion": [],
    "Midjourney": [],
    "DALL-E": ["DALLE", "DALL E"],
    "Whisper": ["OpenAI Whisper"],
    "ElevenLabs": ["Eleven Labs"],
    "GLiDE": ["Fastino"],
    "TypeSafe": [],

    # AI and machine-learning concepts, with the ways postings write them
    "Large Language Models": ["LLM", "LLMs", "large language model", "LLM systems", "LLM APIs", "LLM applications",
                              "LLM-based", "language models", "foundation models", "foundation model"],
    "Generative AI": ["GenAI", "Gen AI", "Gen-AI", "generative artificial intelligence", "GenAI frameworks"],
    "Retrieval-Augmented Generation": ["RAG", "retrieval augmented generation", "RAG pipeline", "RAG pipelines",
                                       "RAG systems", "RAG system", "GraphRAG"],
    "Prompt Engineering": ["prompt design", "prompt orchestration", "prompting", "prompt tuning"],
    "LoRA": ["QLoRA", "PEFT"],

    # AI and machine-learning tools
    "LangChain": ["Lang Chain"],
    "LangExtract": [],
    "DSPy": [],
    "Haystack": [],
    "LiteLLM": [],
    "Langfuse": [],
    "MLflow": ["ML flow"],
    "Weights & Biases": ["wandb", "W&B"],
    "Kubeflow": [],
    "scikit-learn": ["sklearn", "scikit learn", "scikitlearn"],
    "XGBoost": [],
    "LightGBM": [],
    "NumPy": [],
    "Pandas": [],
    "Jupyter": ["Jupyter Notebook", "Jupyter notebooks", "JupyterLab"],
    "OpenCV": [],
    "spaCy": [],
    "NLTK": [],
    "ONNX": [],
    "TensorRT": [],
    "CUDA": [],
    "GPU": ["GPUs", "GPU-based"],
    "n8n": [],
    "Zapier": [],
    "Power Automate": ["Microsoft Power Automate"],
    "UiPath": [],

    # Cloud services, written the long way and the short way
    "Azure Kubernetes Service": ["AKS", "Azure AKS"],
    "Google Kubernetes Engine": ["GKE", "Google GKE"],
    "Kubernetes": ["K8s", "K8", "kube"],
    "OpenShift": ["Red Hat OpenShift"],
    "DynamoDB": ["Amazon DynamoDB", "AWS DynamoDB"],
    "Amazon SQS": ["SQS", "AWS SQS"],
    "Amazon SNS": ["SNS", "AWS SNS"],
    "Amazon Kinesis": ["Kinesis", "AWS Kinesis"],
    "Amazon EMR": ["EMR", "AWS EMR"],
    "Amazon Athena": ["Athena", "AWS Athena"],
    "AWS CDK": ["CDK", "Cloud Development Kit"],
    "AWS IAM": ["AWS Identity and Access Management"],
    "Amazon VPC": ["VPC", "AWS VPC", "virtual private cloud"],
    "AWS Step Functions": ["Step Functions"],
    "Azure Functions": ["Azure Function", "Function Apps"],
    "Azure DevOps": ["ADO", "Azure DevOps pipelines", "Azure Pipelines"],
    "Azure Databricks": [],
    "Azure Data Lake Storage": ["ADLS", "ADLS Gen2", "Azure Data Lake", "Data Lake Storage Gen2"],
    "Azure Event Hubs": ["Event Hubs", "Event Hub"],
    "Azure Service Bus": ["Service Bus"],
    "Azure Cosmos DB": ["Cosmos DB", "CosmosDB"],
    "Azure Monitor": [],
    "Azure Key Vault": ["Key Vault"],
    "Azure Logic Apps": ["Logic Apps"],
    "BigQuery": ["Google BigQuery", "Big Query"],
    "Google Cloud Run": ["Cloud Run"],
    "Google Pub/Sub": ["Pub/Sub", "PubSub", "Cloud Pub/Sub"],
    "Google Dataflow": ["Dataflow"],
    "Google Dataproc": ["Dataproc"],
    "ARM Templates": ["ARM template", "Azure Resource Manager"],
    "Bicep": ["Azure Bicep"],
    "Terraform": ["HashiCorp Terraform", "Terraform modules"],
    "IaaS": ["infrastructure as a service"],
    "PaaS": ["platform as a service"],
    "SaaS": ["software as a service"],

    # Languages, frameworks and databases under their other spellings
    "JavaScript": ["JS", "ECMAScript", "ES6"],
    "TypeScript": ["TS"],
    "Node.js": ["NodeJS", "Node JS", "Node"],
    "React": ["React.js", "ReactJS", "React JS"],
    "Next.js": ["NextJS", "Next JS"],
    "Vue.js": ["Vue", "VueJS", "Vue JS"],
    "Angular": ["AngularJS", "Angular JS"],
    "Python": ["Python3", "Python 3"],
    "PySpark": ["Py Spark"],
    "Spring Boot": ["SpringBoot"],
    "PostgreSQL": ["Postgres", "Postgre SQL"],
    "SQL Server": ["MS SQL", "MSSQL", "Microsoft SQL Server", "MS SQL Server"],
    "T-SQL": ["TSQL", "Transact-SQL"],
    "MongoDB": ["Mongo", "Mongo DB"],
    "Elasticsearch": ["Elastic Search"],
    "OpenSearch": ["Open Search"],
    "Power BI": ["PowerBI"],
    "C++": ["CPP"],
    "Objective-C": ["Objective C", "ObjC"],
    "HTML": ["HTML5"],
    "CSS": ["CSS3"],
    "Tailwind CSS": ["Tailwind", "TailwindCSS"],
    "Swift": [],
    "SwiftUI": ["Swift UI"],
    "UIKit": ["UI Kit"],
    "Xcode": [],
    "React Native": ["ReactNative"],
    "Flutter": [],
    "Salesforce": ["Salesforce.com", "SFDC"],
    "Salesforce Marketing Cloud": ["SFMC", "Marketing Cloud"],
    "MuleSoft": ["Mule Soft", "Mule ESB"],
    "SAP": [],
    "ServiceNow": ["Service Now"],
    "Snowflake": ["Snowflake Data Cloud"],
    "Informatica": ["Informatica PowerCenter", "IICS"],
    "SSIS": ["SQL Server Integration Services"],
    "SSRS": ["SQL Server Reporting Services"],
    "Apache Iceberg": ["Iceberg"],
    "Apache Flink": ["Flink"],
    "Apache Hive": ["Hive"],
    "Apache Beam": ["Beam"],

    # Delivery tools under their other spellings
    "ArgoCD": ["Argo CD", "Argo"],
    "FluxCD": ["Flux CD"],
    "GitHub Actions": ["GH Actions", "GitHub Action"],
    "GitLab CI": ["GitLab CI/CD", "GitLab pipelines"],
    "Jenkins": ["Jenkins pipelines", "Jenkinsfile"],
    "Helm": ["Helm charts", "Helm chart"],
    "Kustomize": [],
    "OpenTelemetry": ["OTel", "Open Telemetry"],
    "ELK Stack": ["ELK", "Elastic Stack"],
    "PagerDuty": ["Pager Duty"],
    "SonarQube": ["Sonar"],
    "Artifactory": ["JFrog", "JFrog Artifactory"],
    "HashiCorp Vault": ["Vault"],
    "PowerShell": ["Power Shell"],
    "Linux": ["GNU/Linux", "RHEL", "Ubuntu", "CentOS", "Unix"],
    "DNS": [],
    "Podman": [],
    "VMware": ["vSphere"],
    "Jira": ["JIRA", "Atlassian Jira"],
    "Confluence": [],


    # Mobile and front end
    "Jetpack Compose": [],
}
