"""Keywords that are not named tools: soft skills, and general terms a posting uses. Standard name -> other wordings.

The match score counts these with less weight than tools. They are kept out of the list of missing tools.
"""

SOFT_SKILLS = {
    "Communication": ["communication skills", "written communication", "verbal communication", "communicator"],
    "Leadership": ["technical leadership", "team leadership", "leading teams"],
    "Mentoring": ["mentorship", "mentor", "coaching"],
    "Collaboration": ["cross-functional collaboration", "cross-functional", "cross functional", "teamwork",
                      "team player", "collaborative"],
    "Stakeholder Management": ["stakeholder engagement", "stakeholder communication", "stakeholders"],
    "Problem Solving": ["problem-solving", "problem solver"],
    "Ownership": ["sense of ownership", "end-to-end ownership"],
    "Accountability": ["accountable"],
    "Adaptability": ["adaptable", "flexibility"],
    "Critical Thinking": [],
    "Analytical Skills": ["analytical", "analytical thinking"],
    "Time Management": ["prioritization", "prioritisation"],
    "Decision Making": ["decision-making"],
    "Negotiation": [],
    "Presentation Skills": ["presentations", "presenting"],
    "Interpersonal Skills": ["interpersonal"],
    "Attention to Detail": ["detail-oriented", "detail oriented"],
    "Initiative": ["self-motivated", "self-starter", "proactive"],
    "Empathy": [],
    "Conflict Resolution": [],
    "Customer Focus": ["customer-focused", "customer centric", "customer-centric"],
    "Strategic Thinking": [],
    "Organizational Skills": ["organisational skills", "organized"],
    "Creativity": ["creative thinking"],
}

OTHER_KEYWORDS = {
    "Agile": ["Agile Methodology", "Agile methodologies", "Scrum", "Kanban", "SAFe Agile"],
    "DevOps": [],
    "Site Reliability Engineering": ["SRE"],
    "Machine Learning": ["ML", "machine-learning"],
    "Observability": [],
    "Monitoring": [],
    "Logging": [],
    "Alerting": [],
    "Automation": [],
    "Scripting": ["shell scripting"],
    "Scalability": ["scalable"],
    "Backend Development": ["back-end", "back end", "backend"],
    "Frontend Development": ["front-end", "front end", "frontend"],
    "Full Stack Development": ["full-stack", "full stack", "fullstack"],
    "Unit Testing": ["unit tests"],
    "Integration Testing": ["integration tests"],
    "Test Automation": ["automated testing", "automation testing"],
    "Performance Testing": ["load testing"],
    "Troubleshooting": ["debugging"],
    "Security": ["cloud security", "application security"],
    "Performance Optimization": ["performance tuning", "performance optimisation"],
    "System Design": [],
    "Distributed Systems": [],
    "High Availability": ["highly available"],
    "Disaster Recovery": [],
    "Incident Management": ["incident response", "postmortems", "postmortem", "root cause analysis", "RCA"],
    "Data Modeling": ["data modelling", "dimensional modeling"],
    "Data Pipelines": ["data pipeline"],
    "Data Warehouse": ["data warehousing"],
    "Data Governance": [],
    "Data Quality": [],
    "Code Review": ["code reviews"],
    "Technical Documentation": ["documentation"],
    "Identity and Access Management": ["IAM"],
    "Role-Based Access Control": ["RBAC"],
    "Networking": [],
    "Cost Optimization": ["cost optimisation", "FinOps"],
    "Event-Driven Architecture": ["event driven architecture", "event-driven"],
    "Solution Architecture": [],
    "Cloud Architecture": [],
}
