"""Common technical skills, each with the other names postings use for it."""

KNOWN_SKILLS = {
    # Cloud platforms and services
    "AWS": ["Amazon Web Services"],
    "Microsoft Azure": ["Azure"],
    "Google Cloud Platform": ["GCP", "Google Cloud"],
    "Amazon EKS": ["EKS", "AWS EKS", "Elastic Kubernetes Service"],
    "Amazon ECS": ["ECS", "AWS ECS"],
    "AWS Lambda": ["Lambda"],
    "Amazon S3": ["S3"],
    "Amazon EC2": ["EC2"],
    "Amazon RDS": ["RDS"],
    "Amazon SageMaker": ["SageMaker", "AWS SageMaker"],
    "Amazon Bedrock": ["Bedrock", "AWS Bedrock"],
    "AWS App Runner": ["App Runner"],
    "AWS CloudFormation": ["CloudFormation"],
    "Amazon CloudWatch": ["CloudWatch", "AWS CloudWatch"],
    "Amazon Redshift": ["Redshift"],
    "AWS Glue": [],
    "Azure Kubernetes Service": ["AKS"],
    "Azure DevOps": [],
    "Azure Data Factory": ["ADF"],
    "Azure Synapse Analytics": ["Synapse"],
    "Google Kubernetes Engine": ["GKE"],
    "Google Cloud Build": ["Cloud Build"],
    "BigQuery": [],
    "Cloudflare": [],
    # Containers, infrastructure and delivery
    "Kubernetes": ["K8s"],
    "Docker": [],
    "Helm": [],
    "Terraform": [],
    "Ansible": [],
    "Pulumi": [],
    "ArgoCD": ["Argo CD"],
    "Jenkins": [],
    "GitHub Actions": [],
    "GitLab CI": ["GitLab CI/CD"],
    "GitHub": [],
    "GitLab": [],
    "Bitbucket": [],
    "Git": [],
    "CI/CD": ["CICD", "continuous integration", "continuous delivery"],
    "NGINX": ["Nginx"],
    "Istio": [],
    "Linux": [],
    "Bash": ["Shell scripting"],
    "YAML": [],
    # Monitoring
    "Prometheus": [],
    "Grafana": [],
    "Datadog": [],
    "Splunk": [],
    "New Relic": [],
    "ELK Stack": ["ELK"],
    "Elasticsearch": [],
    "Kibana": [],
    "OpenTelemetry": [],
    # Languages
    "Python": [],
    "Java": [],
    "JavaScript": [],
    "TypeScript": [],
    "Golang": [],
    "Scala": [],
    "Kotlin": [],
    "Rust": [],
    "C++": [],
    "C#": [],
    "PHP": [],
    "Ruby": [],
    "SQL": [],
    "PL/SQL": [],
    # Frameworks
    "Spring Boot": [],
    "Spring": ["Spring Framework"],
    "Hibernate": [],
    "FastAPI": [],
    "Flask": [],
    "Django": [],
    "Node.js": ["NodeJS", "Node JS"],
    "React": ["React.js", "ReactJS"],
    "Angular": [],
    "Vue.js": ["Vue"],
    ".NET": ["dotnet"],
    "GraphQL": [],
    "REST APIs": ["REST", "RESTful APIs"],
    "Microservices": [],
    "pytest": [],
    "JUnit": [],
    # Data
    "PostgreSQL": ["Postgres"],
    "MySQL": [],
    "Oracle": [],
    "SQL Server": [],
    "MongoDB": [],
    "NoSQL": ["NoSQL databases"],
    "DynamoDB": [],
    "Cassandra": [],
    "Redis": [],
    "Snowflake": [],
    "Databricks": [],
    "Apache Spark": ["Spark", "PySpark"],
    "Apache Kafka": ["Kafka"],
    "Apache Airflow": ["Airflow"],
    "dbt": [],
    "Power BI": [],
    "Tableau": [],
    "Hadoop": [],
    "Delta Lake": [],
    # AI and ML
    "Machine Learning": ["ML"],
    "Generative AI": ["GenAI", "Gen AI"],
    "Large Language Models": ["LLM", "LLMs"],
    "Retrieval-Augmented Generation": ["RAG"],
    "LangChain": [],
    "LangGraph": [],
    "PyTorch": [],
    "TensorFlow": [],
    "scikit-learn": [],
    "Hugging Face": [],
    "vLLM": [],
    "MLflow": [],
    "Prompt Engineering": [],
    "Vector Databases": ["vector database"],
    # Practices
    "Agile": ["Scrum"],
    "DevOps": [],
    "Site Reliability Engineering": ["SRE"],
    "Infrastructure as Code": ["IaC"],
    "GitOps": [],
    "DevSecOps": [],
}
